name: "Development Action"
description: "Deploy to development"

inputs:
  branch:
    description: "Target branch"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Run development job
      shell: bash
      run: echo "Running DEV action for ${{ inputs.branch }}"
