name: "Development Action"
description: "Deploy to development"

inputs:
  branch:
    description: "Target branch"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      shell: bash
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      shell: bash
      run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
