name: "Production Action"
description: "Deploy to production"

inputs:
  branch:
    description: "Target branch"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      shell: bash
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      shell: bash
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
