name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Hello", "Hi", "Greetings"]
    steps:
      - name: Call the other workflow
        uses: ./.github/workflows/called-workflow.yml
        with:
          message: ${{ matrix.message }}
