# .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  push:  # branches を指定しない → 全ブランチ対象

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call the other workflow
        uses: ./.github/workflows/called-workflow.yml
        with:
          message: "Hello from push on branch ${{ github.ref_name }}"
