name: CI

on:
  workflow_dispatch:
  push:

jobs:
  feature-job:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ This runs only on feature/* branches"

  main-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 This runs only on main branch"
