name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - name: 'main'
            production: true
            note: 'foo'
          - name: 'feature/*'
            production: false
            note: 'bar'
          - name: 'develop'
            production: true
            note: 'baz'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Conditional check
        id: check_branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          MATRIX_NAME=${{ matrix.branch.name }}
          REGEX="^${MATRIX_NAME//\*/.*}$"

          RESULT_FILE=result.txt

          if [[ "$BRANCH_NAME" =~ $REGEX ]]; then
            # 後続が実行される → 成功/失敗は後で判定
            echo "matched" > $RESULT_FILE
          else
            echo "⏭️ $BRANCH_NAME did NOT match ${MATRIX_NAME} → skipped" > $RESULT_FILE
            echo "skip=true" >> $GITHUB_ENV
            exit 0
          fi

      - name: Some task
        if: env.skip != 'true'
        run: |
          echo "Running tasks..."
          # exit 1  # ← 失敗ケースを試したいなら有効化

      - name: Save result
        if: always()   # 成功/失敗に関わらず実行
        run: |
          RESULT_FILE=result.txt
          if [ "${{ env.skip }}" = "true" ]; then
            # すでに書かれているので何もしない
            :
          else
            if [ "${{ job.status }}" = "success" ]; then
              echo "✅ ${GITHUB_REF_NAME} matched ${{ matrix.branch.name }} → success" > $RESULT_FILE
            else
              echo "❌ ${GITHUB_REF_NAME} matched ${{ matrix.branch.name }} → failed" > $RESULT_FILE
            fi
          fi

      - name: Upload result artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.branch.name }}
          path: result.txt

  summarize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: results

      - name: Generate summary
        run: |
          echo "## Matrix Results" >> $GITHUB_STEP_SUMMARY
          for file in results/*/result.txt; do
            cat "$file" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          done
