name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - name: 'main'
            production: true
            note: 'foo'
          - name: 'feature/*'
            production: false
            note: 'bar'
          - name: 'develop'
            production: true
            note: 'baz'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Conditional check
        id: check_branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          MATRIX_NAME=${{ matrix.branch.name }}
          REGEX="^${MATRIX_NAME//\*/.*}$"

          if [[ "$BRANCH_NAME" =~ $REGEX ]]; then
            echo "skip=false" >> $GITHUB_ENV
          else
            echo "skip=true" >> $GITHUB_ENV
            echo "⏭️ Branch '$BRANCH_NAME' did NOT match '${MATRIX_NAME}' → skipped" >> $GITHUB_STEP_SUMMARY
            # 即終了（成功扱い）
            exit 0
          fi

      - name: Step 1
        if: env.skip != 'true'
        run: echo "Doing something..."

      - name: Step 2
        if: env.skip != 'true'
        run: |
          echo "Another task"
          # サンプル: わざと失敗させたい場合は以下を有効化
          # exit 1

      - name: Report result
        if: env.skip != 'true'
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Branch '${GITHUB_REF_NAME}' matched '${{ matrix.branch.name }}' → success" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Branch '${GITHUB_REF_NAME}' matched '${{ matrix.branch.name }}' → failed" >> $GITHUB_STEP_SUMMARY
          fi
