name: CI

on:
  workflow_dispatch:
  push:

jobs:
  feature-job:
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: ./.github/workflows/dev.yml
    with:
      branch: ${{ matrix.branch.name }}

  main-job:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/prod.yml
    with:
      branch: ${{ matrix.branch.name }}
