name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - name: 'main'
            production: true
            note: 'foo'
          - name: 'feature/*'
            production: false
            note: 'bar'
          - name: 'develop'
            production: true
            note: 'baz'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Conditional check
        id: check_branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          MATRIX_NAME=${{ matrix.branch.name }}

          # ワイルドカード対応
          REGEX="^${MATRIX_NAME//\*/.*}$"

          if [[ "$BRANCH_NAME" =~ $REGEX ]]; then
            echo "skip=false" >> $GITHUB_ENV
            echo "✅ Branch '$BRANCH_NAME' matched matrix '${MATRIX_NAME}'" >> $GITHUB_STEP_SUMMARY
          else
            echo "skip=true" >> $GITHUB_ENV
            echo "⏭️ Branch '$BRANCH_NAME' did NOT match matrix '${MATRIX_NAME}', skipped." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Step 1
        if: env.skip != 'true'
        run: echo "This runs only if the branch matches matrix"

      - name: Step 2
        if: env.skip != 'true'
        run: echo "Another step that runs only if branch matches matrix"
