name: Development Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  dev-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: echo "Running DEV workflow for ${{ inputs.branch }}"
